# ## Debugging

```php
// Pretty print a var
print_r($var);
var_dump($var);
error_log(json_encode($var));

// Show stack trace
$e = new Exception();
print_r(str_replace('/path/to/code/', '', $e->getTraceAsString()));
```

# map over an array
array_map ( callable $callback , array $array1 [, array $... ] ) : array
# coerce all array items as strings
$a = array_map('strval', $a);

# filter
$input = array(1, 2, 3, 4, 5);
$output = array_filter($input, function ($v) { return $v > 2; });

## Exception

```php
try {
    echo inverse(0) . "\n";
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```
